library(devtools)
source_url('https://raw.githubusercontent.com/MGanslmeier/ExtremeBoundaryAnalysis/master/0helper.R')
source_url('https://raw.githubusercontent.com/MGanslmeier/ExtremeBoundaryAnalysis/master/1overview_table.R')
source_url('https://raw.githubusercontent.com/MGanslmeier/ExtremeBoundaryAnalysis/master/1overview_table.R')
source_url('https://raw.githubusercontent.com/MGanslmeier/ExtremeBoundaryAnalysis/master/2barpie_plot.R')
source_url('https://raw.githubusercontent.com/MGanslmeier/ExtremeBoundaryAnalysis/master/3coeff_plot.R')
source_url('https://raw.githubusercontent.com/MGanslmeier/ExtremeBoundaryAnalysis/master/4distribution_plot.R')
source_url('https://raw.githubusercontent.com/MGanslmeier/ExtremeBoundaryAnalysis/master/5metastat_plot.R')