library(devtools)
source_url('https://raw.githubusercontent.com/MGanslmeier/ExtremeBoundaryAnalysis/master/src/2build_graph/0helper.R')
source_url('https://raw.githubusercontent.com/MGanslmeier/ExtremeBoundaryAnalysis/master/src/2build_graph/1overview_table.R')
source_url('https://raw.githubusercontent.com/MGanslmeier/ExtremeBoundaryAnalysis/master/src/2build_graph/2barpie_plot.R')
source_url('https://raw.githubusercontent.com/MGanslmeier/ExtremeBoundaryAnalysis/master/src/2build_graph/3coeff_plot.R')
source_url('https://raw.githubusercontent.com/MGanslmeier/ExtremeBoundaryAnalysis/master/src/2build_graph/4distribution_plot.R')
source_url('https://raw.githubusercontent.com/MGanslmeier/ExtremeBoundaryAnalysis/master/src/2build_graph/5metastat_plot.R')