library(devtools)
source_url('https://raw.githubusercontent.com/MGanslmeier/ExtremeBoundaryAnalysis/blob/master/src/2build_graph/0helper.R?token=AKADO6G6KNB5IM5OVP2VN4C56QM2O')
source_url('https://raw.githubusercontent.com/MGanslmeier/ExtremeBoundaryAnalysis/blob/master/src/2build_graph/1overview_table.R?token=AKADO6G6KNB5IM5OVP2VN4C56QM2O')
source_url('https://raw.githubusercontent.com/MGanslmeier/ExtremeBoundaryAnalysis/blob/master/src/2build_graph/1overview_table.R?token=AKADO6G6KNB5IM5OVP2VN4C56QM2O')
source_url('https://raw.githubusercontent.com/MGanslmeier/ExtremeBoundaryAnalysis/blob/master/src/2build_graph/2barpie_plot.R?token=AKADO6G6KNB5IM5OVP2VN4C56QM2O')
source_url('https://raw.githubusercontent.com/MGanslmeier/ExtremeBoundaryAnalysis/blob/master/src/2build_graph/3coeff_plot.R?token=AKADO6G6KNB5IM5OVP2VN4C56QM2O')
source_url('https://raw.githubusercontent.com/MGanslmeier/ExtremeBoundaryAnalysis/blob/master/src/2build_graph/4distribution_plot.R?token=AKADO6G6KNB5IM5OVP2VN4C56QM2O')
source_url('https://raw.githubusercontent.com/MGanslmeier/ExtremeBoundaryAnalysis/blob/master/src/2build_graph/5metastat_plot.R?token=AKADO6G6KNB5IM5OVP2VN4C56QM2O')